
# Modify aesthetics and add Guide to navbar
website:
  title: "Stat 20 Staff Guide"
  open-graph:
    site-name: "Stat 20 Staff Guide"
  navbar:
    title: false
    background: warning
    left:
      - text: Guide
        href: staff-guide/index.qmd
  sidebar:
    - title: "Guide"
      style: floating
      align: left
      contents:
        - staff-guide/index.qmd
        - staff-guide/roles-and-expectations.qmd
        - staff-guide/grading.qmd
        - staff-guide/website.qmd
        - staff-guide/pre-semester-checklist.qmd