# If running locally, first source assets/scripts/ignore_future_docs.R
project:
  output-dir: _site-ignore-future
  post-render: assets/scripts/unignore_future_docs.R

website:
  title: "Stat 20"
  navbar:
    title: " "
    background: white