# If running locally, first source assets/scripts/ignore_future_docs.R
project:
  type: website
  output-dir: _site/stat20-staff-guide
    
# Website Configuration and Layout
website:
  title: "Stat 20 Staff Guide"
  page-navigation: true
  repo-actions: [edit, issue]
  open-graph:
    site-name: "Stat 20 Staff Guide"
  reader-mode: true
  navbar:
    title: false
    background: warning
    left:
      - text: Guide
        href: staff-guide/index.qmd
  sidebar:
    - title: "Guide"
      style: floating
      align: left
      contents:
        - staff-guide/index.qmd
        - staff-guide/roles-and-expectations.qmd
    - title: "Notes"
      style: floating
      align: left
      collapse-level: 1
      contents:
        - section: "Questions and Data"
          contents:
            - 1-questions-and-data/01-understanding-the-world/notes.qmd
            - 1-questions-and-data/02-taxonomy-of-data/notes.qmd
            - 1-questions-and-data/03-a-tool-for-computing-with-data/notes.qmd
        - section: "Describing Data"
          contents:
            - 2-describing-data/04-summarizing-categorical-data/notes.qmd
            - 2-describing-data/05-summarizing-numerical-data/notes.qmd
            - 2-describing-data/06-a-grammar-of-graphics/notes.qmd
            - 2-describing-data/07-conditioning/notes.qmd
            - 2-describing-data/08-communicating-with-graphics/notes.qmd
            - 2-describing-data/09-summarizing-associations/notes.qmd
            - 2-describing-data/10-multiple-linear-regression/notes.qmd
        - section: "Generalization"
          contents:
            - 3-generalization/11-chance-intro/notes.qmd
            - 3-generalization/12-cond-prob-indep/notes.qmd
            - 3-generalization/13-random-variables/notes.qmd
            - 3-generalization/14-ev-se/notes.qmd
            - 3-generalization/15-sampling-distributions/notes.qmd
            - 3-generalization/16-confidence-intervals/notes.qmd
            - 3-generalization/17-hypothesis-tests/notes.qmd
