project:
  type: website
  resources:
    - "homepage-readings"
    - "4-generalization/labs/05-peoples-park/references"
  render:
    - "*.qmd"
    - "!2-summarizing-data/04-conditioning/ps.qmd"
    - "!2-summarizing-data/05-communicating-with-graphics/ps.qmd"
    - "!2-summarizing-data/06-summarizing-associations/ps.qmd"
    - "!3-probability/03-random-variables/ps-2.qmd"

# Website Configuration and Layout
website:
  title: "Stat 20"
  description: "Introduction to Probability and Statistics at UC Berkeley"
  search:
    location: navbar
    type: overlay
  site-url: "https://www.stat20.org/"
  repo-url: "https://github.com/stat20/course-materials"
  favicon: assets/favicon.ico
  image: assets/stat20-hex.png
  open-graph:
    site-name: "Stat 20"
    image: assets/stat20-hex.png
  twitter-card: true
  page-navigation: true
  reader-mode: true
  navbar:
    title: false
    logo: assets/stat20-hex-small.png
    logo-alt: "Stat 20 logo"
    background: white
    foreground: "gray-800"
    collapse-below: sm
    left:
      - text: Syllabus
        href: syllabus.qmd
      - text: Schedule
        href: schedule.qmd
      - text: Notes
        href: notes.qmd
      - text: Assignments
        href: assignments.qmd
    tools:
      - icon: chat-fill
        href: https://edstem.org/us/courses/42631
        aria-label: Ed Discussion Forum
      - icon: bar-chart-fill
        href: https://www.gradescope.com/courses/571644
        aria-label: Gradescope
      - icon: r-circle-fill
        href: https://stat20.datahub.berkeley.edu/
        aria-label: RStudio
        
  page-footer: 
    background: white
    foreground: "gray-800"
    border: false
    right:
      - text: License
        href: license.qmd
    left:
      - text: "This site is hosted by Netlify."
        href: https://www.netlify.com/


# Format-specific Metadata
format:
  html:
    theme:
      - sandstone
      - assets/styles.scss
    toc: true
    published-title: "class date"
    reference-location: document
    code-fold: true
    code-link: true
    code-summary: ""

# General Metadata
execute:
  freeze: false
  message: false
  warning: false
  fig-align: center
  
profile:
  default: toc
