project:
  type: default
  
format:
  html:
    theme: 
      - sandstone
      - ../../assets/styles.scss
  
  revealjs:
    author: "STAT 20: Introduction to Probability and Statistics"
    height: 900
    width: 1600
    theme: ../../assets/slides.scss
    multiplex: false
    transition: fade
    slide-number: c
    incremental: false 
    center: false
    menu: false
    highlight-style: github
    progress: false
    code-overflow: wrap
    title-slide-attributes:
      data-background-size: contain
      data-background-color: #f8f5f0
    