project:
  type: default
  output-dir: _output

# Format-specific Metadata
format:
  html:
    theme:
      - sandstone
      - assets/styles.scss
    toc: true
    published-title: "class date"
    reference-location: document
    code-fold: true
    code-link: true
    code-summary: ""

# General Metadata
execute:
  freeze: auto
  message: false
  warning: false
  fig-align: center
