
schedule:
  - week: 1
    days:
      - display-date: "Aug 1"
        title: "Understanding the World"
        items:
          - type: Notes
            href: foo/notes.qmd
          - type: Slides
            href: foo/slides.qmd
          - type: PS
            href: foo/ps.qmd
      - display-date: "Aug 3"
        title: "Taxonomy of Data"
        items:
          - type: Notes
            href: foo2/notes.qmd
          - type: Slides
            href: foo2/slides.qmd
          - type: PS
            href: foo2/ps.qmd
  - week: 2
    days:
      - display-date: "Aug 4"
        title: "A Tool for Computing with Data"
        items:
          - type: Notes
            href: foo/notes.qmd
          - type: Slides
            href: foo/slides.qmd
          - type: PS
            href: foo/ps.qmd
      - display-date: "Aug 6"
        title: "Summarizing Categorical Data"
        items:
          - type: Notes
            href: foo2/notes.qmd
          - type: Slides
            href: foo2/slides.qmd
          - type: PS
            href: foo2/ps.qmd
  - week: 3
    days:
      - display-date: "Aug 8"
        title: "Summarizing Numerical Data"
        items:
          - type: Notes
            href: foo/notes.qmd
          - type: Slides
            href: foo/slides.qmd
          - type: PS
            href: foo/ps.qmd
      - display-date: "Aug 10"
        title: "A Grammar of Graphics"
        items:
          - type: Notes
            href: foo2/notes.qmd
          - type: Slides
            href: foo2/slides.qmd
          - type: PS
            href: foo2/ps.qmd
