---
title: "Cancer Diagnosis"
subtitle: "Lab"
format: stat20handout-typst
---

In this lab you will train and evaluate a classification algorithm to determine whether or not a [fine needle aspiration biopsy](https://en.wikipedia.org/wiki/Fine-needle_aspiration) is cancerous (malignant) or non-cancerous (benign). The data were downloaded from the [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29) and lightly processed. Here is a brief glimpse at some of the columns. Use this glimpse to answer the following questions. 

```{r}
#| echo: false
#| warning: false
library(tidyverse)
cells <- read_csv(
  "data/wdbc.data",
  col_names = c(
    "id",
    "diagnosis",
    "radius_mean",
    "texture_mean",
    "perimeter_mean",
    "area_mean",
    "smoothness_mean",
    "compactness_mean",
    "concavity_mean",
    "concave_points_mean",
    "symmetry_mean",
    "fractal_dimension_mean",
    "radius_se",
    "texture_se",
    "perimeter_se",
    "area_se",
    "smoothness_se",
    "compactness_se",
    "concavity_se",
    "concave_points_se",
    "symmetry_worst",
    "fractal_dimension_worst",
    "radius_worst",
    "texture_worst",
    "perimeter_worst",
    "area_worst",
    "smoothness_worst",
    "compactness_worst",
    "concavity_worst",
    "concave_points_worst",
    "symmetry_worst",
    "fractal_dimension_worst"
  )
) |>
  mutate(diagnosis = factor(diagnosis, levels = c("B", "M")))

set.seed(57)
knitr::kable(
  cells |>
    slice_sample(n = 23, replace = FALSE) |>
    select(diagnosis, radius_mean, area_mean, radius_se)
)
```


@.  What is the unit of observation in this data frame?

\

@. We will be fitting models to output a diagnosis ("benign" or "malignant"). This is a categorical outcome. Which level will be considered the reference level by default in R and why?

\

\

\

@.  If you were to deploy your method in a clinical setting to help diagnose cancer, would it be worse to misclassify a benign case or to misclassify a malignant case? Explain your rationale in at least two sentences.

\newpage


@.  Based on the glimpse, use a plot to compare the `radius_mean` for benign vs. malignant biopsies, *side-by-side*. Make sure to give your label your axes and give your plot a title. Give a shape which matches **your** expectation of the phenomenon and explain your choice in at least one sentence.


\
\
\
\
\
\
\
\
\
\

@.  Based on your previous sketch, what biopsies are you prepared to classify as malignant versus benign? Fill in the blanks below to make a decision rule. 

    ```
If radius_mean > ________: predict ________
  Otherwise predict ________
    ```

@. Modify the side-by-side plot you made earlier to visually represent the decision rule. 

\




@. Based on the glimpse, sketch a plot that examines the association between two predictors, `radius_mean` and `area_mean`. Make sure to give your label your axes and give your plot a title. Give a shape which matches **your** expectation of the phenomenon and explain your choice in at least one sentence.


\
\
\
\
\
\
\
\
\
\
\
\
\
\
\



<!---
@. Based on the glimpse, sketch a single plot that examines the association between `radius_mean` and `radius_sd` separately for each diagnosis (hint: there should be *three* variables depicted on your plot). Give a shape which matches **your** expectation of the phenomenon and explain your choice in at least one sentence. Do you think the relationship between `radius_mean` and `area_mean` will be different for each diagnosis, and why? Explain in at least once sentence.

\

\

\

\

\

\
--->

@. In many realms of medicine, classification algorithms can be more accurate than the most well-trained medical doctors. What is gained and what is lost by shifting to algorithmic diagnoses? Although a book could be written about this topic, please answer in one paragraph.

\

\

\






