on:
  workflow_dispatch:
  push:
    branches: main
name: "Publish Staff Guide"
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
      - name: Render and Publish
        shell: bash
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          QUARTO_PROFILE: staff-guide
        run: |
          quarto publish netlify --id 33fedc67-c501-4720-bd24-6e00c15aa700