on:
  pull_request:
    branches: main
jobs:
  publish:
    name: publish to stat20staff netlify
    runs-on: ubuntu-latest
    steps:
      # for accessing this repo's assets in the container
      - name: Check out the repo
        uses: actions/checkout@v3
      # run the container, attaching this repo as a working directory
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
           QUARTO_PROFILE: staff-site
        with:
          image: stat20/stat20-docker:latest
          options: -v ${{ github.workspace }}:/home/rstudio/stat20 -e NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} -e QUARTO_PROFILE=staff-site
          shell: bash
          run: |
            # execute from the textbook
            cd /home/rstudio/stat20/

            # _freeze probably won't exist, but lets document that it shouldn't
            rm -rf ./_freeze

            # this doesn't always succeed
            r ./assets/scripts/propagate-dates.r || true

            r ./assets/scripts/write-toc.r

            quarto publish netlify --id 33fedc67-c501-4720-bd24-6e00c15aa700
