on:
  workflow_dispatch:
  pull_request:
    branches: next-semester
  
name: "Publish to stat20-next-semester.netlify.app"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # for accessing this repo's assets in the container
      - name: Check out the repo
        uses: actions/checkout@v3
      # run the container, attaching this repo as a working directory
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
           QUARTO_PROFILE: full-site
        with:
          image: stat20/stat20-docker:latest
          options: -v ${{ github.workspace }}:/home/rstudio/stat20 -e NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }}
          shell: bash
          run: |
            # exit if any command returns non-zero exit
            set -e

            # execute from the textbook
            cd /home/rstudio/stat20/
            
            # ignore future files from render list
            quarto run asset/scripts/autopublish.ts
            
            # render site and upload to stat20-next-semester.netlify.app
            quarto publish netlify --id 71793655-483e-4d50-aec7-de1381435888
